"""Actualizar modelo Sale con nuevos campos

Revision ID: 02b3a206c7d1
Revises: 
Create Date: 2025-04-17 14:59:17.813687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b3a206c7d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('client_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('ticket_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('sale_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('commission',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('travel_date')
        batch_op.drop_column('passenger_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('travel_date', sa.DATE(), nullable=False))
        batch_op.alter_column('commission',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('sale_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('ticket_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status')
        batch_op.drop_column('client_email')
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
