"""Añadir campos de verificación de correo electrónico

Revision ID: 60b3ef362ec8
Revises: 02b3a206c7d1
Create Date: 2025-04-22 13:36:50.455899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3ef362ec8'
down_revision = '02b3a206c7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_confirm_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_confirm_date')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
